module.exports ={
    message:{
        highest:"最高价",
        lowest:"最低价",
        in:"点击进入",
        exchange:"交易所",
        todayTake:"今日可领",
        ranking:"领取排行",
        jingyubi:"鲸鱼币可领取",
        bonus:"分红领取MCC",
        todayGrant:"今日发放鲸鱼币总额",
        todayReceive:"今日可领取鲸鱼币",
        receive:"领取",
        weekReceive:"本周可领取MCC币",
        weekGrant:"本周发放MCC币总额",
        jingyuRank:"鲸鱼币领取排名",
        MCCranking:"MCC币领取排名",
        noReceipt:"今日暂无领取",
        noRanking:"暂无排行",
        record:"领取记录"
    }
}